src/SphinxQL.php
tests/classes/SphinxQLTest.php

How do you feel about adding this?

Allow possibility to pass array as select argument

---

src/SphinxQL.php
tests/SphinxQL/SphinxQLTest.php

See also: http://sphinxsearch.com/blog/2013/05/14/subselects/

Support subselects

---

.travis.yml

This seems to be quite a bit faster.  You can close #61.

travis-ci: switch to container builds

---

src/Match.php
src/SphinxQL.php
tests/SphinxQL/MatchTest.php
tests/SphinxQL/SphinxQLTest.php

Any opinions on the api I implemented?

Add match expression query builder

---

src/Drivers/Mysqli/Connection.php
src/Drivers/Mysqli/MultiResultSet.php
src/Drivers/Mysqli/ResultSet.php
src/Drivers/Pdo/MultiResultSet.php
src/Drivers/Pdo/ResultSet.php
src/SphinxQL.php
tests/SphinxQL/ConnectionTest.php
tests/SphinxQL/MatchTest.php
tests/SphinxQL/MultiResultSetTest.php
tests/SphinxQL/SphinxQLTest.php
tests/travis/mysqli.phpunit.xml
tests/travis/pdo.phpunit.xml

classes 33% -> 54%, methods 62% -> 81%, lines 75% -> 93%
Fixed a few small bugs in the process.

Improve test coverage

---

src/Drivers/Mysqli/Connection.php
src/Helper.php

It is an issue when `ping()` shows up in the profiler...

Improve quoting performance

---

.gitignore
.travis.yml
src/Drivers/ConnectionBase.php
src/Drivers/MultiResultSetBase.php
src/Drivers/Mysqli/Connection.php
src/Drivers/Mysqli/MultiResultSet.php
src/Drivers/Mysqli/ResultSet.php
src/Drivers/Pdo/Connection.php
src/Drivers/Pdo/MultiResultSet.php
src/Drivers/Pdo/ResultSet.php
src/Drivers/ResultSetBase.php
src/Drivers/ResultSetInterface.php
src/Drivers/SimpleConnection.php
src/Helper.php
src/SphinxQL.php
tests/README.md
tests/SphinxQL/ConnectionTest.php
tests/SphinxQL/FacetTest.php
tests/SphinxQL/HelperTest.php
tests/SphinxQL/ResultSetTest.php
tests/SphinxQL/SphinxQLTest.php
tests/sphinx.conf
tests/test_udf.c

Note that tests now require gcc to compile the test udf (see tests/README.md), and restart searchd (if it is running) to pick up the change to the conf file.

Refactor duplicate code into base classes; add a few more tests

---

README.md
src/Helper.php
tests/SphinxQL/HelperTest.php

Added optimize Index.
I think this could be helpfull for others as well

Added optimizeIndex to Helper class

---

README.md
src/Helper.php
tests/SphinxQL/HelperTest.php

Added showIndexStatus & flushRamchunk to Helper class

Added showIndexStatus & flushRamchunk to Helper class

---

src/Drivers/Mysqli/Connection.php

There were a lot of unnecessary overhead for calling ping every time `query`, `multiQuery` or `escape` is called. From 0e3cd15a5748c9e0a446285efdef9f96457ac359, it seems like we only needed to ensure the connection is present.

Remove overhead of pinging server if connection is established

---

src/Drivers/ConnectionBase.php
tests/SphinxQL/ConnectionTest.php

return 0/1 when quoting boolean values

---

src/Drivers/ConnectionBase.php

Hey!
Property is null by default, not needed to declare it as null be default again
And Added @var PHPDocblock
Thanks

Up code quality

---

src/SphinxQL.php
tests/SphinxQL/SphinxQLTest.php

Enable calling set() multiple times for multi inserts

---

src/SphinxQL.php
tests/SphinxQL/SphinxQLTest.php

add check to only add non-empty compiled match queries

---

src/SphinxQL.php

Fix use the short array push syntax on a string

---

src/Helper.php

I've fixed very strange way of using connection property in Helper class
- there is no need it to be public
- there is no need to create and use its getter as it wright there and protected

fix using connection class property in Helper

---

src/Drivers/ConnectionBase.php
src/Drivers/MultiResultSetBase.php
src/Drivers/Mysqli/Connection.php
src/Drivers/Mysqli/MultiResultSetAdapter.php
src/Drivers/Mysqli/ResultSetAdapter.php
src/Drivers/Pdo/MultiResultSetAdapter.php
src/Drivers/Pdo/ResultSet.php
src/Drivers/Pdo/ResultSetAdapter.php
src/Drivers/ResultSetBase.php
src/Facet.php
src/Match.php
src/SphinxQL.php

All class properties are defined with null value, except they don't have defaults.
So this is no nessesary to force setting them to null, because they are already null

fix properties nulling by deafaut

---

src/Facet.php
src/Match.php

Well, I've fixed create methods in Facet and Match to return static not exact class objects
Changes to Match, Helper were made earlier

fix create methods in Facet and Match

---

src/Facet.php
src/Helper.php
src/Match.php
src/SphinxQL.php

Well, I've fixed some phpDocs in Facet, Helper, Match, SphinxQL classes
Now they are not highligthed by ide

fix phpDoc in Facet, Helper, Match, SphinxQL

---

.travis.yml
README.md
composer.json
docs/intro.rst
src/Drivers/Pdo/Connection.php
src/Drivers/Pdo/MultiResultSet.php

i updated php requirements
and after that i'll create 2 more PRs with modifications based on newer php

update php requirements >=5.6

---

.travis.yml
tests/install.sh
tests/ms_test_udf.c
tests/run.sh
tests/sphinx.conf

This changes the CI build matrix to test the following `searchd`.
- Sphinx 2
- Sphinx 3 (Currently Not Working)
- Manticore

update CI build matrix

---

src/Drivers/Mysqli/Connection.php
tests/SphinxQL/ConnectionTest.php

add guard to mb_internal_encoding() for mysqli driver

---

CHANGELOG.md
README.md

Update readme to not use the depricated class, and also update the changelog about this class.

Fix Bug 162

---

src/Drivers/Pdo/Connection.php

Add the exception code and the previous throwable when re-throw exceptions

Add the exception code and the previous throwable

---

composer.json

remove php <= 7.0 and phpunit 5/6

drop php <= 7.0
